#! /bin/sh
# /etc/init.d/auriol-pluv-read

### BEGIN INIT INFO
# Provides:          auriol-pluv-read
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Simple script to start a program at boot
### END INIT INFO

# Carry out specific functions when asked to by the system
case "$1" in
  start)
    echo "Starting auriol-pluv-read"
    # run application you want to start
    /home/pi/auriol_pluviometer_reader/auriol-restarter.sh
    ;;
  stop)
    echo "Stopping auriol-pluv-read"
    # kill application you want to stop
    killall auriol-pluviometer-reader
    ;;
  *)
    echo "Usage: /etc/init.d/auriol-pluv-read {start|stop}"
    exit 1
    ;;
esac

exit 0


